name: linked-list

dependencies:
  - base

library:
  exposed-modules: Deque
  source-dirs: src
  dependencies:
    - containers
    - stm

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - linked-list
      - hspec
