name: hamming

dependencies:
  - base

library:
  exposed-modules: Hamming
  source-dirs: src
  dependencies:

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - hamming
      - hspec
