name: binary

dependencies:
  - base

library:
  exposed-modules: Binary
  source-dirs: src
  dependencies:

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - binary
      - hspec
