name: grains

dependencies:
  - base

library:
  exposed-modules: Grains
  source-dirs: src
  dependencies:

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - grains
      - hspec
