name: queen-attack

dependencies:
  - base

library:
  exposed-modules: Queens
  source-dirs: src
  dependencies:

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - queen-attack
      - hspec
