name: matrix

dependencies:
  - base
  - vector

library:
  exposed-modules: Matrix
  source-dirs: src
  dependencies:
    - split

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - matrix
      - hspec
