name: prime-factors

dependencies:
  - base

library:
  exposed-modules: PrimeFactors
  source-dirs: src
  dependencies:

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - prime-factors
      - hspec
