name: clock

dependencies:
  - base

library:
  exposed-modules: Clock
  source-dirs: src
  dependencies:

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - clock
      - hspec
