name: sublist

dependencies:
  - base

library:
  exposed-modules: Sublist
  source-dirs: src
  dependencies:

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sublist
      - hspec
