name: accumulate

dependencies:
  - base

library:
  exposed-modules: Accumulate
  source-dirs: src
  dependencies:

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - accumulate
      - hspec
