name: gigasecond

dependencies:
  - base
  - time

library:
  exposed-modules: Gigasecond
  source-dirs: src
  dependencies:

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - gigasecond
      - hspec
